services:
  auth-service:
    build:
      context: ./auth-service
    ports:
      - "8080:8080"
    networks:
      - monorepo-net

  user-service:
    build:
      context: ./user-service
    ports:
      - "8081:8081"
    networks:
      - monorepo-net

networks:
  monorepo-net:
